controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_config:
    path: /api/config
    controller: App\Controller\ApiController::getApiMeteo
    methods: [GET]